### ISSUE TITLE
Cannot connect to AP after some time

### ISSUE THREAD

**Issue by MartinLoeper** [txn2/txwifi#14]
* **I'm submitting a ...**
  - [ x ] bug report

* **What is the current behavior?**
After ~1h I am not able to connect to the access point (uap0) anymore.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

1. Start the docker container as described in the README.
2. Do stuff for about an hour. 
3. Disconnect mobile phone from access point.
4. Try to reconnect...

* **What is the expected behavior?**
It should be possible to connect to the access point at any time.   
There should be at least the possibility to detect the error condition and restart the access point.   
Otherwise clients won't be able to connect and have to manually restart the whole device.

* **What is the motivation / use case for changing the behavior?**
I am exploring the stability of this project in order to deploy it on a fleet of IoT devices.

* **Please tell us about your environment:**
  
  - Device: Huawei Honor 9 Smatphone (client) + Raspberry Pi rev. 4 (server)
  - OS: Android + Raspbian Lite (Buster)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Do you have any idea how I could start to debug this issue and gather additional information? Much appreciated! =)

Possibly related to https://github.com/cjimti/iotwifi/issues/18

**Comment by cjimti** [comment]
This seems to be a limitation with the wifi on the Raspberry Pi. This is not detectable since the interface reports that it is up and even continues to broadcast the ssid.

The original use-case is for booting a device and configuring wifi access for that device (like Nest or Echo.) So it's not a bug that has had an impact on projects that use it that way.

If you are aware of a solution please let me know. I am also open to pull requests.

**Comment by MartinLoeper** [comment]
Thanks for responding! I will look into this and post an update as soon as we find something.

**Comment by MartinLoeper** [comment]
Just a quick notice for others which find themselves in the same situation:

I bought the *Edimax EW-7811UN* WIFI dongle and have rewritten the code in our fork of this repository to work with both: integrated rpi WIFI (AP mode) and the external Edimax dongle (station mode).

This combination is far more stable and suits our usecase better.

**Comment by peterlolty** [comment]
This is a bug in this project instead of a limitation, due to the hostapd routine channel variable 'messages' is not fetched anymore after the function return, which block the stdout of hostapd proceess, and thus the process has no respond afterall. You may find the solution here, https://github.com/txn2/txwifi/pull/26/commits/db72b517b25a186fedf2fe35406077cc1fc2cc64

**Comment by MartinLoeper** [comment]
Thanks for pointing this out @peterlolty! We will try out your fix :+1:
