### ISSUE TITLE
uap0 IP address not assigned correct

### ISSUE THREAD

**Issue by bilalilyas90** [txn2/txwifi#9]
* **I'm submitting a ...**
  - [x] support request

Hi
I am trying to make raspberry pi 3 Access point and I have done all the steps given .
But I am unable to connect to access point.
it always says failed to obtain IP address on mobile or laptop.
In terminal it assigns correct IP to uap0 but on desktop wifi connect section it does not assign IP and no device can connect to Access point.
Please help me .. its urgent

**Comment by cjimti** [comment]
@bilalilyas90 you have not really described a bug or given any information to help understand the problem. Unfortunately, I don't have any time in my schedule these days to help with support requests (I need to remove that as an option). You might try some online forums on networking.

**Comment by danbachar** [comment]
Hi @cjimti,
I'm experiencing a similar issue as @bilalilyas90; in my case, the IP address passed from the configuration file isn't respected, and uap0 gets assigned a random IP address, not related even to the submask of the default ip address. However, after running `sudo ifconfig uap0 192.168.27.1`, uap0 gets assigned the correct IP address.
I'm running it on an raspberry pi 3 running 2019-04-08-raspbian-stretch-lite, and have followed your instructions.

Also, not sure if this is related, but the network spawned by the docker container is sometimes unjoinable because of a wrong password. Sometimes removing the container, rebooting etc helps.
